parameters:
    tms_media.storage_mapper.class: Tms\Bundle\MediaBundle\StorageMapper\StorageMapper

services:

    ## Managers ##

    tms_media.manager.media:
        class: Tms\Bundle\MediaBundle\Manager\MediaManager
        arguments:
            - "%tms_media.configuration%"
            - "@doctrine.orm.entity_manager"
            - "@event_dispatcher"
            - "@knp_gaufrette.filesystem_map"
            - "%tms_media.cache_directory%"


    ## Metadata Extrators ##

    tms_media.metadata_extractor.image:
        class: Tms\Bundle\MediaBundle\MetadataExtractor\ImageMetadataExtractor
        public: false
        tags:
            - { name: tms_media.metadata_extractor }
    # Keep the default metadata extractor in last position
    tms_media.metadata_extractor.default:
        class: Tms\Bundle\MediaBundle\MetadataExtractor\DefaultMetadataExtractor
        public: false
        tags:
            - { name: tms_media.metadata_extractor }


    ## Media Transformers ##

    tms_media.transformer.document:
        class: Tms\Bundle\MediaBundle\Media\Transformer\DocumentMediaTransformer
        public: false
        tags:
            - { name: tms_media.transformer }
    tms_media.transformer.image:
        class: Tms\Bundle\MediaBundle\Media\Transformer\ImageMediaTransformer
        arguments: ["%tms_media.cache_directory%"]
        public: false
        tags:
            - { name: tms_media.transformer }
    tms_media.transformer.rest:
        class: Tms\Bundle\MediaBundle\Media\Transformer\RestMediaTransformer
        arguments: ["@idci_exporter.manager"]
        public: false
        tags:
            - { name: tms_media.transformer }
    tms_media.transformer.svg:
        class: Tms\Bundle\MediaBundle\Media\Transformer\SvgMediaTransformer
        arguments: [%tms_media.cache_directory%]
        public: false
        tags:
            - { name: tms_media.transformer }
    tms_media.transformer.unica:
        class: Tms\Bundle\MediaBundle\Media\Transformer\UnicaMediaTransformer
        arguments: ["%tms_media.cache_directory%", "%knp_gaufrette.adapters.batch_media.local.directory%"]
        public: false
        tags:
            - { name: tms_media.transformer }
    # Keep the default transformer in last position
    tms_media.transformer.default:
        class: Tms\Bundle\MediaBundle\Media\Transformer\DefaultMediaTransformer
        public: false
        tags:
            - { name: tms_media.transformer }
